#### to run this file make sure to download the dataset from this link https://ai.stanford.edu/~amaas/data/sentiment/aclImdb_v1.tar.gz

In [1]:
import pandas as pd 
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import os
import re

### loading the data

In [2]:
reviews = []
lables = []

positive_reviews = os.path.join("aclImdb/train/pos")
negative_reviews = os.path.join("aclImdb/train/neg")
for file in os.listdir(positive_reviews):
    with open(os.path.join(positive_reviews, file), 'r') as f:
        reviews.append((f.read()).lower())
        lables.append(1)
for file in os.listdir(negative_reviews):
    with open(os.path.join(negative_reviews, file), 'r') as f:
        reviews.append((f.read()).lower())
        lables.append(0)
train_data = pd.DataFrame({"review": reviews, "label": lables})
train_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   review  25000 non-null  object
 1   label   25000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 390.8+ KB

### preprocessign the text

In [3]:
train_data["review"] = train_data["review"].apply(lambda x: re.sub(r"[^\w ]", " ", x))
train_data["review"] = train_data["review"].apply(lambda x: x.split())
train_data.head()

                                              review  label
0  [bromwell, high, is, a, cartoon, comedy, it, r...      1
1  [homelessness, or, houselessness, as, george, ...      1
2  [brilliant, over, acting, by, lesley, ann, war...      1
3  [this, is, easily, the, most, underrated, film...      1
4  [this, is, not, the, typical, mel, brooks, fil...      1

### creating the vocab

In [4]:
vocab = {}
index = 0
for review in train_data["review"]:
    for word in review:
        if word not in vocab:
            vocab[word] = index
            index += 1
print(vocab)

{'bromwell': 0, 'high': 1, 'is': 2, 'a': 3, 'cartoon': 4, 'comedy': 5, 'it': 6, 'ran': 7, 'at': 8, 'the': 9, 'same': 10, 'time': 11, 'as': 12, 'some': 13, 'other': 14, 'programs': 15, 'about': 16, 'school': 17, 'life': 18, 'such': 19, 'teachers': 20, 'my': 21, '35': 22, 'years': 23, 'in': 24, 'teaching': 25, 'profession': 26, 'lead': 27, 'me': 28, 'to': 29, 'believe': 30, 'that': 31, 's': 32, 'satire': 33, 'much': 34, 'closer': 35, 'reality': 36, 'than': 37, 'scramble': 38, 'survive': 39, 'financially': 40, 'insightful': 41, 'students': 42, 'who': 43, 'can': 44, 'see': 45, 'right': 46, 'through': 47, 'their': 48, 'pathetic': 49, 'pomp': 50, 'pettiness': 51, 'of': 52, 'whole': 53, 'situation': 54, 'all': 55, 'remind': 56, 'schools': 57, 'i': 58, 'knew': 59, 'and': 60, 'when': 61, 'saw': 62, 'episode': 63, 'which': 64, 'student': 65, 'repeatedly': 66, 'tried': 67, 'burn': 68, 'down': 69, 'immediately': 70, 'recalled': 71, 'classic': 72, 'line': 73, 'inspector': 74, 'm': 75, 'here': 76, 'sack': 77, 'one': 78, 'your': 79, 'welcome': 80, 'expect': 81, 'many': 82, 'adults': 83, 'age': 84, 'think': 85, 'far': 86, 'fetched': 87, 'what': 88, 'pity': 89, 'isn': 90, 't': 91, 'homelessness': 92, 'or': 93, 'houselessness': 94, 'george': 95, 'carlin': 96, 'stated': 97, 'has': 98, 'been': 99, 'an': 100, 'issue': 101, 'for': 102, 'but': 103, 'never': 104, 'plan': 105, 'help': 106, 'those': 107, 'on': 108, 'street': 109, 'were': 110, 'once': 111, 'considered': 112, 'human': 113, 'did': 114, 'everything': 115, 'from': 116, 'going': 117, 'work': 118, 'vote': 119, 'matter': 120, 'most': 121, 'people': 122, 'homeless': 123, 'just': 124, 'lost': 125, 'cause': 126, 'while': 127, 'worrying': 128, 'things': 129, 'racism': 130, 'war': 131, 'iraq': 132, 'pressuring': 133, 'kids': 134, 'succeed': 135, 'technology': 136, 'elections': 137, 'inflation': 138, 'if': 139, 'they': 140, 'll': 141, 'be': 142, 'next': 143, 'end': 144, 'up': 145, 'streets': 146, 'br': 147, 'you': 148, 'given': 149, 'bet': 150, 'live': 151, 'month': 152, 'without': 153, 'luxuries': 154, 'had': 155, 'home': 156, 'entertainment': 157, 'sets': 158, 'bathroom': 159, 'pictures': 160, 'wall': 161, 'computer': 162, 'treasure': 163, 'like': 164, 'goddard': 165, 'bolt': 166, 'lesson': 167, 'mel': 168, 'brooks': 169, 'directs': 170, 'stars': 171, 'plays': 172, 'rich': 173, 'man': 174, 'world': 175, 'until': 176, 'deciding': 177, 'make': 178, 'with': 179, 'sissy': 180, 'rival': 181, 'jeffery': 182, 'tambor': 183, 'he': 184, 'thirty': 185, 'days': 186, 'succeeds': 187, 'do': 188, 'wants': 189, 'future': 190, 'project': 191, 'making': 192, 'more': 193, 'buildings': 194, 'where': 195, 'thrown': 196, 'bracelet': 197, 'his': 198, 'leg': 199, 'monitor': 200, 'every': 201, 'move': 202, 'step': 203, 'off': 204, 'sidewalk': 205, 'nickname': 206, 'pepto': 207, 'by': 208, 'vagrant': 209, 'after': 210, 'written': 211, 'forehead': 212, 'meets': 213, 'characters': 214, 'including': 215, 'woman': 216, 'name': 217, 'molly': 218, 'lesley': 219, 'ann': 220, 'warren': 221, 'ex': 222, 'dancer': 223, 'got': 224, 'divorce': 225, 'before': 226, 'losing': 227, 'her': 228, 'pals': 229, 'sailor': 230, 'howard': 231, 'morris': 232, 'fumes': 233, 'teddy': 234, 'wilson': 235, 'are': 236, 'already': 237, 'used': 238, 're': 239, 'survivors': 240, 'not': 241, 'reaching': 242, 'mutual': 243, 'agreements': 244, 'being': 245, 'fight': 246, 'flight': 247, 'kill': 248, 'killed': 249, 'love': 250, 'connection': 251, 'between': 252, 'wasn': 253, 'necessary': 254, 'plot': 255, 'found': 256, 'stinks': 257, 'observant': 258, 'films': 259, 'prior': 260, 'shows': 261, 'tender': 262, 'side': 263, 'compared': 264, 'slapstick': 265, 'blazing': 266, 'saddles': 267, 'young': 268, 'frankenstein': 269, 'spaceballs': 270, 'show': 271, 'having': 272, 'something': 273, 'valuable': 274, 'day': 275, 'hand': 276, 'stupid': 277, 'don': 278, 'know': 279, 'money': 280, 'maybe': 281, 'should': 282, 'give': 283, 'instead': 284, 'using': 285, 'monopoly': 286, 'this': 287, 'film': 288, 'will': 289, 'inspire': 290, 'others': 291, 'brilliant': 292, 'over': 293, 'acting': 294, 'best': 295, 'dramatic': 296, 'hobo': 297, 'lady': 298, 'have': 299, 'ever': 300, 'seen': 301, 'scenes': 302, 'clothes': 303, 'warehouse': 304, 'second': 305, 'none': 306, 'corn': 307, 'face': 308, 'good': 309, 'anything': 310, 'take': 311, 'lawyers': 312, 'also': 313, 'superb': 314, 'accused': 315, 'turncoat': 316, 'selling': 317, 'out': 318, 'boss': 319, 'dishonest': 320, 'lawyer': 321, 'shrugs': 322, 'indifferently': 323, 'says': 324, 'three': 325, 'funny': 326, 'words': 327, 'jeffrey': 328, 'favorite': 329, 'later': 330, 'larry': 331, 'sanders': 332, 'fantastic': 333, 'too': 334, 'mad': 335, 'millionaire': 336, 'crush': 337, 'ghetto': 338, 'character': 339, 'malevolent': 340, 'usual': 341, 'hospital': 342, 'scene': 343, 'invade': 344, 'demolition': 345, 'site': 346, 'classics': 347, 'look': 348, 'legs': 349, 'two': 350, 'big': 351, 'diggers': 352, 'fighting': 353, 'bleeds': 354, 'movie': 355, 'gets': 356, 'better': 357, 'each': 358, 'quite': 359, 'often': 360, 'easily': 361, 'underrated': 362, 'inn': 363, 'cannon': 364, 'sure': 365, 'its': 366, 'flawed': 367, 'does': 368, 'realistic': 369, 'view': 370, 'unlike': 371, 'say': 372, 'how': 373, 'citizen': 374, 'kane': 375, 'gave': 376, 'lounge': 377, 'singers': 378, 'titanic': 379, 'italians': 380, 'idiots': 381, 'jokes': 382, 'fall': 383, 'flat': 384, 'still': 385, 'very': 386, 'lovable': 387, 'way': 388, 'comedies': 389, 'pull': 390, 'story': 391, 'traditionally': 392, 'reviled': 393, 'members': 394, 'society': 395, 'truly': 396, 'impressive': 397, 'fisher': 398, 'king': 399, 'crap': 400, 'either': 401, 'only': 402, 'complaint': 403, 'cast': 404, 'someone': 405, 'else': 406, 'director': 407, 'writer': 408, 'so': 409, 'typical': 410, 'was': 411, 'less': 412, 'movies': 413, 'actually': 414, 'followable': 415, 'leslie': 416, 'made': 417, 'she': 418, 'under': 419, 'rated': 420, 'actress': 421, 'there': 422, 'moments': 423, 'could': 424, 'fleshed': 425, 'bit': 426, 'probably': 427, 'cut': 428, 'room': 429, 'worth': 430, 'price': 431, 'rent': 432, 'overall': 433, 'himself': 434, 'job': 435, 'characteristic': 436, 'speaking': 437, 'directly': 438, 'audience': 439, 'again': 440, 'actor': 441, 'fume': 442, 'both': 443, 'played': 444, 'parts': 445, 'well': 446, 'comedic': 447, 'robin': 448, 'williams': 449, 'nor': 450, 'quirky': 451, 'insane': 452, 'recent': 453, 'thriller': 454, 'fame': 455, 'hybrid': 456, 'drama': 457, 'dramatization': 458, 'mixed': 459, 'new': 460, 'per': 461, 'se': 462, 'mystery': 463, 'suspense': 464, 'vehicle': 465, 'attempts': 466, 'locate': 467, 'sick': 468, 'boy': 469, 'keeper': 470, 'starring': 471, 'sandra': 472, 'oh': 473, 'rory': 474, 'culkin': 475, 'pretty': 476, 'news': 477, 'report': 478, 'william': 479, 'close': 480, 'achieving': 481, 'goal': 482, 'must': 483, 'highly': 484, 'entertained': 485, 'though': 486, 'fails': 487, 'teach': 488, 'guide': 489, 'inspect': 490, 'amuse': 491, 'felt': 492, 'watching': 493, 'guy': 494, 'performing': 495, 'actions': 496, 'third': 497, 'person': 498, 'perspective': 499, 'real': 500, 'able': 501, 'subscribe': 502, 'premise': 503, 'watch': 504, 'definitely': 505, 'friday': 506, 'saturday': 507, 'night': 508, 'fare': 509, 'rates': 510, '7': 511, '10': 512, 'fiend': 513, 'yes': 514, 'art': 515, 'successfully': 516, 'slow': 517, 'paced': 518, 'unfolds': 519, 'nice': 520, 'volumes': 521, 'even': 522, 'notice': 523, 'happening': 524, 'fine': 525, 'performance': 526, 'sexuality': 527, 'angles': 528, 'seem': 529, 'unnecessary': 530, 'affect': 531, 'enjoy': 532, 'however': 533, 'core': 534, 'engaging': 535, 'doesn': 536, 'rush': 537, 'onto': 538, 'grips': 539, 'enough': 540, 'keep': 541, 'wondering': 542, 'direction': 543, 'use': 544, 'lights': 545, 'achieve': 546, 'desired': 547, 'affects': 548, 'unexpectedness': 549, '1': 550, 'looking': 551, 'lay': 552, 'back': 553, 'hear': 554, 'thrilling': 555, 'short': 556, 'critically': 557, 'acclaimed': 558, 'psychological': 559, 'based': 560, 'true': 561, 'events': 562, 'gabriel': 563, 'celebrated': 564, 'late': 565, 'talk': 566, 'host': 567, 'becomes': 568, 'captivated': 569, 'harrowing': 570, 'listener': 571, 'adoptive': 572, 'mother': 573, 'toni': 574, 'collette': 575, 'troubling': 576, 'questions': 577, 'arise': 578, 'finds': 579, 'drawn': 580, 'into': 581, 'widening': 582, 'hides': 583, 'deadly': 584, 'secret': 585, 'according': 586, 'official': 587, 'synopsis': 588, 'really': 589, 'stop': 590, 'reading': 591, 'these': 592, 'comments': 593, 'now': 594, 'lose': 595, 'ending': 596, 'ms': 597, 'planning': 598, 'chopped': 599, 'sent': 600, 'deleted': 601, 'land': 602, 'overkill': 603, 'nature': 604, 'physical': 605, 'mental': 606, 'ailments': 607, 'obvious': 608, 'mr': 609, 'returns': 610, 'york': 611, 'possibly': 612, 'blindness': 613, 'question': 614, 'revelation': 615, 'certain': 616, 'highway': 617, 'video': 618, 'tape': 619, 'would': 620, 'benefit': 621, 'editing': 622, 'bobby': 623, 'cannavale': 624, 'jess': 625, 'initially': 626, 'believable': 627, 'couple': 628, 'establishing': 629, 'relationship': 630, 'might': 631, 'helped': 632, 'set': 633, 'stage': 634, 'otherwise': 635, 'exemplary': 636, 'offers': 637, 'exceptionally': 638, 'strong': 639, 'characterization': 640, 'gay': 641, 'impersonation': 642, 'anna': 643, 'joe': 644, 'morton': 645, 'ashe': 646, 'pete': 647, 'logand': 648, 'perfect': 649, 'donna': 650, 'belongs': 651, 'creepy': 652, 'hall': 653, 'correct': 654, 'saying': 655, 'psycho': 656, 'several': 657, 'organizations': 658, 'giving': 659, 'awards': 660, 'seemed': 661, 'reach': 662, 'women': 663, 'due': 664, 'slighter': 665, 'dispersion': 666, 'roles': 667, 'certainly': 668, 'noticed': 669, 'award': 670, 'consideration': 671, 'patrick': 672, 'stettner': 673, 'evokes': 674, 'hitchcock': 675, 'makes': 676, 'getting': 677, 'sandwich': 678, 'vending': 679, 'machine': 680, 'suspenseful': 681, 'finally': 682, 'writers': 683, 'armistead': 684, 'maupin': 685, 'terry': 686, 'anderson': 687, 'deserve': 688, 'gratitude': 689, 'attendants': 690, 'everywhere': 691, '21': 692, '06': 693, '2006': 694, '2': 695, 'john': 696, 'cullum': 697, 'lisa': 698, 'emery': 699, 'becky': 700, 'baker': 701, 'dir': 702, 'hitchcockian': 703, 'suspenser': 704, 'gives': 705, 'stand': 706, 'low': 707, 'key': 708, 'celebrities': 709, 'fans': 710, 'near': 711, 'paranoia': 712, 'associates': 713, 'why': 714, 'almost': 715, 'norm': 716, 'latest': 717, 'derange': 718, 'fan': 719, 'scenario': 720, 'no': 721, 'radio': 722, 'personality': 723, 'named': 724, 'reads': 725, 'stories': 726, 'penned': 727, 'airwaves': 728, 'accumulated': 729, 'interesting': 730, 'form': 731, 'submitted': 732, 'manuscript': 733, 'travails': 734, 'troubled': 735, 'youth': 736, 'editor': 737, 'read': 738, 'naturally': 739, 'disturbed': 740, 'ultimately': 741, 'intrigued': 742, 'nightmarish': 743, 'existence': 744, 'abducted': 745, 'sexually': 746, 'abused': 747, 'rescued': 748, 'nurse': 749, 'excellent': 750, 'adopted': 751, 'correspondence': 752, 'reveals': 753, 'dying': 754, 'aids': 755, 'meet': 756, 'suddenly': 757, 'doubt': 758, 'devious': 759, 'ulterior': 760, 'motives': 761, 'seed': 762, 'planted': 763, 'estranged': 764, 'lover': 765, 'whose': 766, 'sudden': 767, 'departure': 768, 'city': 769, 'apartment': 770, 'emotional': 771, 'tailspin': 772, 'grown': 773, 'tempest': 774, 'teacup': 775, 'decides': 776, 'investigating': 777, 'backgrounds': 778, 'discovering': 779, 'truths': 780, 'didn': 781, 'anticipate': 782, 'co': 783, 'wrote': 784, 'screenplay': 785, 'former': 786, 'novice': 787, 'hoax': 788, 'run': 789, 'full': 790, 'tilt': 791, 'any': 792, 'old': 793, 'fashioned': 794, 'pot': 795, 'boiler': 796, 'helps': 797, 'conflicted': 798, 'hearted': 799, 'genuinely': 800, 'number': 801, 'fact': 802, 'him': 803, 'thing': 804, 'escaped': 805, 'own': 806, 'unsettling': 807, 'dreadful': 808, 'trait': 809, 'leave': 810, 'unmentioned': 811, 'underlines': 812, 'desperation': 813, 'rattle': 814, 'runs': 815, 'gas': 816, 'eventually': 817, 'repetitive': 818, 'predictable': 819, 'despite': 820, 'finely': 821, 'directed': 822, 'piece': 823, 'hoodwink': 824, 'pays': 825, 'listen': 826, 'inner': 827, 'voice': 828, 'careful': 829, 'hope': 830, 'god': 831, 'bless': 832, 'constantly': 833, 'shooting': 834, 'foot': 835, 'lately': 836, 'dumb': 837, 'done': 838, 'decade': 839, 'perhaps': 840, 'exception': 841, 'death': 842, 'smoochy': 843, 'bombed': 844, 'came': 845, 'cult': 846, 'dramas': 847, 'especially': 848, 'insomnia': 849, 'hour': 850, 'photo': 851, 'mediocre': 852, 'reviews': 853, 'quick': 854, 'dvd': 855, 'release': 856, 'among': 857, 'period': 858, 'chilling': 859, 'include': 860, 'serial': 861, 'killer': 862, 'anyone': 863, 'physically': 864, 'dangerous': 865, 'concept': 866, 'actual': 867, 'case': 868, 'fraud': 869, 'yet': 870, 'officially': 871, 'confirmed': 872, 'autobiography': 873, 'child': 874, 'anthony': 875, 'godby': 876, 'johnson': 877, 'suffered': 878, 'horrific': 879, 'abuse': 880, 'contracted': 881, 'result': 882, 'moved': 883, 'reports': 884, 'online': 885, 'may': 886, 'exist': 887, 'confused': 888, 'feelings': 889, 'brilliantly': 890, 'portrayed': 891, 'resurfaced': 892, 'mind': 893, 'sociopathic': 894, 'caretaker': 895, 'role': 896, 'cry': 897, 'little': 898, 'miss': 899, 'sunshine': 900, 'times': 901, 'looked': 902, 'camera': 903, 'thought': 904, 'staring': 905, 'takes': 906, 'play': 907, 'sort': 908, 'understated': 909, 'reviewed': 910, 'actresses': 911, 'generation': 912, 'nominated': 913, 'academy': 914, '2008': 915, 'incredible': 916, 'least': 917, 'scary': 918, 'dark': 919, 'recommend': 920, 'prepared': 921, 'unsettled': 922, 'because': 923, 'leaves': 924, 'strange': 925, 'feeling': 926, 'first': 927, 'maupins': 928, 'taken': 929, 'displayed': 930, 'cares': 931, 'loves': 932, 'said': 933, 'we': 934, 'version': 935, 'expected': 936, 'past': 937, 'gloss': 938, 'hollywood': 939, 'succeeded': 940, 'amount': 941, 'restraint': 942, 'captures': 943, 'fragile': 944, 'essence': 945, 'lets': 946, 'us': 947, 'struggle': 948, 'issues': 949, 'trust': 950, 'personnel': 951, 'around': 952, 'introduced': 953, 'players': 954, 'reminded': 955, 'nothing': 956, 'seems': 957, 'smallest': 958, 'event': 959, 'change': 960, 'our': 961, 'lives': 962, 'irrevocably': 963, 'request': 964, 'review': 965, 'book': 966, 'turns': 967, 'changing': 968, 'find': 969, 'strength': 970, 'within': 971, 'carry': 972, 'forward': 973, 'bad': 974, 'avoid': 975, 'average': 976, 'american': 977, 'serious': 978, 'please': 979, 'chance': 980, 'touches': 981, 'darkness': 982, 'go': 983, 'ourselves': 984, 'stepped': 985, 'another': 986, 'quality': 987, 'forget': 988, 'steals': 989, '1940': 990, 'leading': 991, 'looks': 992, 'screen': 993, 'presence': 994, 'hacks': 995, 'opinion': 996, 'liked': 997, 'action': 998, 'tense': 999, 'opening': 1000, 'semi': 1001, 'truck': 1002, 'transitional': 1003, 'filmed': 1004, 'ways': 1005, 'lapse': 1006, 'photography': 1007, 'unusual': 1008, 'colors': 1009, 'evil': 1010, 'd': 1011, '8': 1012, 'illnesses': 1013, 'born': 1014, 'modern': 1015, 'constant': 1016, 'vigilance': 1017, 'accrued': 1018, 'information': 1019, 'realm': 1020, 'pyschosis': 1021, 'kept': 1022, 'psychologists': 1023, 'counselors': 1024, 'psychiatrists': 1025, 'busy': 1026, 'last': 1027, 'them': 1028, 'decades': 1029, 'occasionally': 1030, 'phenomenon': 1031, 'discover': 1032, 'knowledge': 1033, 'remedy': 1034, 'entitled': 1035, 'listner': 1036, 'tells': 1037, 'popular': 1038, 'called': 1039, 'noon': 1040, 'spends': 1041, 'evenings': 1042, 'enthralling': 1043, 'audiences': 1044, 'vivid': 1045, 'lifestyles': 1046, 'authentic': 1047, 'veneer': 1048, 'causes': 1049, 'admit': 1050, 'longer': 1051, 'abandoned': 1052, 'friend': 1053, 'seeks': 1054, 'shelter': 1055, 'deepening': 1056, 'despair': 1057, 'isolation': 1058, 'mysterious': 1059, 'asks': 1060, 'needs': 1061, 'feel': 1062, 'useful': 1063, 'reaches': 1064, 'desperate': 1065, '14': 1066, 'year': 1067, 'peter': 1068, 'depicts': 1069, 'early': 1070, 'sexual': 1071, 'hands': 1072, 'brutal': 1073, 'parents': 1074, 'soon': 1075, 'en': 1076, 'wrapped': 1077, 'elusive': 1078, 'bizarre': 1079, 'tale': 1080, 'torn': 1081, 'medical': 1082, 'nightmare': 1083, 'pure': 1084, 'pop': 1085, 'comical': 1086, 'prove': 1087, 'performances': 1088, 'enjoyed': 1089, 'summer': 1090, 'entire': 1091, 'notes': 1092, 'adds': 1093, 'wonderful': 1094, 'comic': 1095, 'touch': 1096, 'great': 1097, 'mom': 1098, 'goes': 1099, 'top': 1100, 'everyone': 1101, 'half': 1102, 'general': 1103, 'nine': 1104, 'minutes': 1105, 'shorter': 1106, 'sundance': 1107, 'wonder': 1108, 'disturbing': 1109, 'images': 1110, 'told': 1111, 'straightforward': 1112, 'fashion': 1113, 'refreshing': 1114, 'directors': 1115, 'impress': 1116, 'rather': 1117, 'tell': 1118, 'sucker': 1119, 'punched': 1120, 'previews': 1121, 'ads': 1122, 'want': 1123, 'expecting': 1124, 'disappointed': 1125, 'left': 1126, 'imagination': 1127, 'minor': 1128, 'quibble': 1129, 'somewhat': 1130, 'odd': 1131, 'different': 1132, 'guarantee': 1133, 'kind': 1134, 'won': 1135, 'pacing': 1136, 'plus': 1137, 'come': 1138, 'intriguing': 1139, 'content': 1140, 'americanized': 1141, 'neither': 1142, 'secrets': 1143, 'hard': 1144, 'determine': 1145, 'outcome': 1146, 'hell': 1147, 'damn': 1148, 'original': 1149, 'previous': 1150, 'commenters': 1151, 'foundations': 1152, 'happened': 1153, 'delivery': 1154, 'waste': 1155, 'eerie': 1156, 'waiting': 1157, 'get': 1158, 'needed': 1159, 'across': 1160, 'canadian': 1161, 'few': 1162, 'seasons': 1163, 'x': 1164, 'files': 1165, 'cheap': 1166, 'hokey': 1167, 'jump': 1168, 'seat': 1169, 'reached': 1170, 'moment': 1171, 'then': 1172, 'faded': 1173, 'away': 1174, 'false': 1175, 'climax': 1176, 'part': 1177, 'tries': 1178, 'fix': 1179, 'problems': 1180, 'held': 1181, 'attention': 1182, 'shining': 1183, 'enamored': 1184, 'friendship': 1185, 'ill': 1186, 'met': 1187, 'contact': 1188, 'talking': 1189, 'telephone': 1190, 'boyfriend': 1191, 'raises': 1192, 'prompts': 1193, 'arrange': 1194, 'meeting': 1195, 'follows': 1196, 'permanent': 1197, 'impact': 1198, 'memorable': 1199, 'portrayal': 1200, 'starred': 1201, 'inspired': 1202, 'somber': 1203, 'silence': 1204, 'throughout': 1205, 'thanks': 1206, 'seeing': 1207, 'logic': 1208, 'anyway': 1209, 'added': 1210, 'bonus': 1211, 'recommended': 1212, 'storyteller': 1213, 'scraggy': 1214, 'hushed': 1215, 'hypnotic': 1216, 'tones': 1217, 'acquainted': 1218, 'friends': 1219, 'fourteen': 1220, 'wisconsin': 1221, 'detailing': 1222, 'boot': 1223, 'compels': 1224, 'further': 1225, 'since': 1226, 'partner': 1227, 'happens': 1228, 'survivor': 1229, 'hiv': 1230, 'acquaints': 1231, 'guardian': 1232, 'discovers': 1233, 'stetner': 1234, 'moves': 1235, 'lot': 1236, 'faster': 1237, '90': 1238, 'min': 1239, 'genre': 1240, 'keeps': 1241, 'storyline': 1242, 'lean': 1243, 'clear': 1244, 'various': 1245, 'holes': 1246, 'sew': 1247, 'openings': 1248, 'detail': 1249, 'except': 1250, 'familiar': 1251, 'works': 1252, 'personal': 1253, 'loop': 1254, 've': 1255, 'loved': 1256, 'heard': 1257, 'narration': 1258, 'personally': 1259, 'supporting': 1260, 'waitress': 1261, 'restaurant': 1262, 'collete': 1263, 'frequents': 1264, 'small': 1265, 'notch': 1266, 'mood': 1267, 'established': 1268, 'namely': 1269, 'chilly': 1270, 'lonely': 1271, 'exteriors': 1272, 'terrific': 1273, 'framing': 1274, 'ends': 1275, 'tie': 1276, 'together': 1277, 'particularly': 1278, 'compelling': 1279, 'stick': 1280, 'draws': 1281, 'hints': 1282, 'lurking': 1283, 'tension': 1284, 'mild': 1285, 'mannered': 1286, 'relate': 1287, 'obsession': 1288, 'fares': 1289, 'intentions': 1290, 'production': 1291, 'rushed': 1292, 'apparent': 1293, 'feels': 1294, 'preview': 1295, 'complete': 1296, 'effort': 1297, 'taupin': 1298, 'commendable': 1299, 'absolutely': 1300, 'completely': 1301, 'enthralled': 1302, 'gripping': 1303, 'intense': 1304, 'spot': 1305, 'lite

### turning the reviews into bag of words representation (using sparse vectorization method)

In [10]:
def create_bow(review):
    bow = {}
    for word in review:
        if word in vocab:
            if vocab[word] in bow:
                bow[vocab[word]] += 1
            else:
                bow[vocab[word]] = 1
    return bow

train_data["review_bow"] = train_data["review"].apply(create_bow)
train_data.head()

,review,label,review_bow
0,"[bromwell, high, is, a, cartoon, comedy, it, r...",1,"{0: 4, 1: 5, 2: 4, 3: 4, 4: 1, 5: 1, 6: 2, 7: ..."
1,"[homelessness, or, houselessness, as, george, ...",1,"{92: 1, 93: 8, 94: 1, 12: 5, 95: 1, 96: 1, 97:..."
2,"[brilliant, over, acting, by, lesley, ann, war...",1,"{292: 1, 293: 1, 294: 1, 208: 1, 219: 1, 220: ..."
3,"[this, is, easily, the, most, underrated, film...",1,"{287: 2, 2: 4, 361: 1, 9: 6, 121: 2, 362: 1, 2..."
4,"[this, is, not, the, typical, mel, brooks, fil...",1,"{287: 2, 2: 3, 241: 1, 9: 8, 410: 1, 168: 1, 1..."

### computing class priors

In [6]:
priors = train_data["label"].value_counts(normalize=True).to_dict()
print(priors)

{1: 0.5, 0: 0.5}

### computing likelihoods for word using laplace smoothing

In [7]:
positive_train_data = train_data[train_data["label"] == 1]
negative_train_data = train_data[train_data["label"] == 0]
likelihoods = {}
for word, index in vocab.items():
    likelihoods[index] = {
        1: (positive_train_data["review_bow"].apply(lambda x: x.get(index, 0)).sum() + 1) / (positive_train_data["review_bow"].apply(lambda x: sum(x.values())).sum() + len(vocab)),
        0: (negative_train_data["review_bow"].apply(lambda x: x.get(index, 0)).sum() + 1) / (negative_train_data["review_bow"].apply(lambda x: sum(x.values())).sum() + len(vocab))
    }

### loading test data

In [12]:
reviews = []
lables = []

positive_reviews = os.path.join("aclImdb/test/pos")
negative_reviews = os.path.join("aclImdb/test/neg")
for file in os.listdir(positive_reviews):
    with open(os.path.join(positive_reviews, file), 'r') as f:
        reviews.append((f.read()).lower())
        lables.append(1)
for file in os.listdir(negative_reviews):
    with open(os.path.join(negative_reviews, file), 'r') as f:
        reviews.append((f.read()).lower())
        lables.append(0)
test_data = pd.DataFrame({"review": reviews, "label": lables})
test_data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 25000 entries, 0 to 24999
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   review  25000 non-null  object
 1   label   25000 non-null  int64
dtypes: int64(1), object(1)
memory usage: 390.8+ KB

### preprocessing test data

In [13]:
test_data["review"] = test_data["review"].apply(lambda x: re.sub(r"[^\w ]", " ", x))
test_data["review"] = test_data["review"].apply(lambda x: x.split())
test_data["review_bow"] = test_data["review"].apply(create_bow)
test_data.head()

,review,label,review_bow
0,"[i, went, and, saw, this, movie, last, night, ...",1,"{58: 7, 2337: 1, 60: 4, 62: 2, 287: 3, 355: 4,..."
1,"[actor, turned, director, bill, paxton, follow...",1,"{441: 1, 3382: 1, 407: 1, 2184: 1, 2185: 3, 11..."
2,"[as, a, recreational, golfer, with, some, know...",1,"{12: 3, 3: 3, 38793: 1, 70988: 1, 179: 2, 13: ..."
3,"[i, saw, this, film, in, a, sneak, preview, an...",1,"{58: 3, 62: 1, 287: 5, 288: 3, 24: 1, 3: 6, 10..."
4,"[bill, paxton, has, taken, the, true, story, o...",1,"{2184: 1, 2185: 1, 98: 1, 929: 1, 9: 20, 561: ..."

### generating predictions

In [ ]:
predictions = []
for _, row in test_data.iterrows():
    positive_prob = priors[1]
    negative_prob = priors[0]
    for index, count in row["review_bow"].items():
        positive_prob *= likelihoods[index][1] ** count
        negative_prob *= likelihoods[index][0] ** count
    if positive_prob > negative_prob:
        predictions.append(1)
    else:
        predictions.append(0)

In [16]:
model_accuracy = np.mean(np.array(predictions) == test_data["label"])
print(f"Accuracy: {model_accuracy}")

Accuracy: 0.55072

In [18]:
predictions = []
for _, row in test_data.iterrows():
    log_positive_prob = np.log(priors[1])
    log_negative_prob = np.log(priors[0])
    for index, count in row["review_bow"].items():
        log_positive_prob += count * np.log(likelihoods[index][1])
        log_negative_prob += count * np.log(likelihoods[index][0])
    if log_positive_prob > log_negative_prob:
        predictions.append(1)
    else:
        predictions.append(0)

In [19]:
model_accuracy = np.mean(np.array(predictions) == test_data["label"])
print(f"Accuracy: {model_accuracy}")

Accuracy: 0.81016